elasticsearch:
  ports:
    - "9200:9200"
    - "9300:9300"
  environment:
    discovery.type: single-node
logstash:
  ports:
    - "5000:5000"
    - "5000:5000/udp"
  environment:
    # otherwise logstash will keep sending its own logs to itself over and
    # over... not fun
    LOGSPOUT: ignore
  volumes:
     - "./dockerfiles/logstash/pipeline/:/usr/share/logstash/pipeline/"
kibana:
  ports:
    - "5601:5601"
