elasticsearch:
  ports:
    - "9200:9200"
    - "9300:9300"
logstash:
  ports:
    - "5000:5000"
    - "5000:5000/udp"
  environment:
    # otherwise logstash will keep sending its own logs to itself over and
    # over... not fun
    LOGSPOUT: ignore 
  command: -f /etc/logstash.sample.conf
kibana:
  ports:
    - "5601:5601"
