elasticsearch:
  extends:
    file: docker-compose-common.yml
    service: elasticsearch
  image: docker.elastic.co/elasticsearch/elasticsearch:5.6.1
logstash:
  extends:
    file: docker-compose-common.yml
    service: logstash
  image: docker.elastic.co/logstash/logstash:5.6.1
  links:
    - elasticsearch:elasticsearch
kibana:
  extends:
    file: docker-compose-common.yml
    service: kibana
  image: docker.elastic.co/kibana/kibana:5.6.1
  links:
    - elasticsearch:elasticsearch
