elasticsearch:
  ports:
    - "9200:9200"
    - "9300:9300"
  environment:
    discovery.type: single-node
  image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
logstash:
  ports:
    - "5000:5000"
  environment:
    # Do not log to logspout, if present. Otherwise logstash will keep sending its own logs to itself over and over...
    LOGSPOUT: ignore
  volumes:
     - "./logstash/pipeline/:/usr/share/logstash/pipeline/"
  image: docker.elastic.co/logstash/logstash:5.6.3
  links:
    - elasticsearch:elasticsearch
kibana:
  ports:
    - "5601:5601"
  image: docker.elastic.co/kibana/kibana:5.6.3
  links:
    - elasticsearch:elasticsearch
